version: '3'

services:
  dbpgsql:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: CHANGEME
      POSTGRES_PASSWORD: CHANGEME123

  redis:
    image: redis:4.0.10
    restart: always
    ports:
      - "63792:6379"
    volumes:
      - redis_data:/data
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

volumes:
  redis_data: